module.exports = {
  content: ["_layouts/**/*.html", "_includes/**/*.html", "_posts/**/*.md", "*.html"],
  css: ["assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    "collapse",
    "collapsing",
    "show",
    "dropdown-menu",
    "dropdown-item",
    "table",
    "table-dark",
    "table-hover",
    "table-responsive",
    "af-tooltip",
    "af-popover",
    "font-weight-bold",
    "font-weight-medium",
    "font-weight-lighter",
    "navbar",
    "container",
    "fixed-top",
    "nav-item",
    "nav-link",
    "row",
    "col",
  ],
};
